---

global:
  registry: ''

# io-onboarding-pa - start

ioOnboardingPa:

  replicaCount: 1

  images:
    backend:
      repository: teamdigitale/io-onboarding-pa
      tag: latest
      pullPolicy: IfNotPresent
    postgresDb:
      repository: postgres
      tag: 12-alpine
      pullPolicy: IfNotPresent

  backend:
    host: backend

  postgresDb:
    host: postgres_db
    database: io-onboarding-pa
    user: io-onboarding-pa

  services:
    backendHttp:
      port: 3000
    postgresDb:
      port: 5432

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    path: /
    hosts:
      - pa-onboarding.io.italia.it
    tls:
      - hosts:
          - pa-onboarding.io.italia.it
        secretName: io-onboarding-pa-tls

  resources:
    # For each of the following objects, set limits
    # removing the curly brackets after resources and
    # uncommenting the lines below.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    ckan: {}
    solr: {}
    redis: {}
    postgresDb: {}

  nodeSelector: {}

  tolerations: {}

  affinity: {}

# io-onboarding-pa - end
