---

apiVersion: v1
kind: Secret
metadata:
  name: app-backend-secrets
type: Opaque

---

{{- $azureSecretName := .Values.appBackend.secrets.azureSecretNamePrefix -}}
{{- $azureKeyvaultName := .Values.appBackend.secrets.azureKeyvaultName -}}
{{- $kubernetesSecretName := .Values.appBackend.secrets.kubernetesSecretName -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: {{ $azureSecretName }}
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ $azureKeyvaultName }}
    object:
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretName }}
      type: multi-key-value-secret
      contentType: application/x-json
  output:
    secret:
      # Name of the secret in Kubernetes
      name: {{ $kubernetesSecretName }}

---

{{- $azureSecretNamePrefix := .Values.appBackend.secrets.azureSecretNamePrefix -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the certificate to retrieve from the Azure Keyvault
  name: {{ $azureSecretNamePrefix }}-spid-certs
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.appBackend.secrets.azureKeyvaultName }}
    object:
      type: certificate
      # Name of the certificate to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-spid-certs
  output:
    secret:
      name: {{ .Values.appBackend.secrets.kubernetesSpidCertsSecretName }}
      type: kubernetes.io/tls
