---

apiVersion: v1
kind: Secret
metadata:
  name: app-backend-secrets
type: Opaque

---

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: k8s-app-backend-secrets-api-key
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.appBackend.azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-app-backend-secrets-api-key
  output:
    secret:
      # Name of the secret in Kubernetes
      name: app-backend-secrets
      # Name of key in the secret in Kubernetes
      dataKey: api_key

---

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: k8s-app-backend-secrets-nh-endpoint
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.appBackend.azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-app-backend-secrets-nh-endpoint
  output:
    secret:
      # Name of the secret in Kubernetes
      name: app-backend-secrets
      # Name of key in the secret in Kubernetes
      dataKey: azure_nh_endpoint

---

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: k8s-app-backend-secrets-pre-shared-key
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.appBackend.azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-app-backend-secrets-pre-shared-key
  output:
    secret:
      # Name of the secret in Kubernetes
      name: app-backend-secrets
      # Name of key in the secret in Kubernetes
      dataKey: azure_pre_shared_key

---

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: k8s-app-backend-secrets-redis-password
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.appBackend.azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: k8s-app-backend-secrets-redis-password
  output:
    secret:
      # Name of the secret in Kubernetes
      name: app-backend-secrets
      # Name of key in the secret in Kubernetes
      dataKey: azure_redis_password
