---

apiVersion: v1
kind: Secret
metadata:
  name: pagopa-proxy-secrets
type: Opaque

---

{{- $azureSecretNamePrefix := .Values.pagopaProxy.secrets.azureSecretNamePrefix -}}
{{- $azureKeyvaultName := .Values.pagopaProxy.secrets.azureKeyvaultName -}}
{{- $kubernetesSecretName := .Values.pagopaProxy.secrets.kubernetesSecretName -}}

{{- range .Values.pagopaProxy.secrets.azureSecretNameSuffixes }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: {{ $azureSecretNamePrefix }}-{{ . }}
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ $azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-{{ . }}
  output:
    secret:
      # Name of the secret in Kubernetes
      name: {{ $kubernetesSecretName }}
      # Name of key in the secret in Kubernetes
      dataKey: {{ regexReplaceAll "-" . "_" }}
---
{{- end }}
