---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pagopaProxy.secrets.kubernetesSecretName }}
type: Opaque

---

{{- $azureSecretName := .Values.pagopaProxy.secrets.azureSecretNamePrefix -}}
{{- $azureKeyvaultName := .Values.pagopaProxy.secrets.azureKeyvaultName -}}
{{- $kubernetesSecretName := .Values.pagopaProxy.secrets.kubernetesSecretName -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: {{ $azureSecretName }}
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ $azureKeyvaultName }}
    object:
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretName }}
      type: multi-key-value-secret
      contentType: application/x-json
  output:
    secret:
      # Name of the secret in Kubernetes
      name: {{ $kubernetesSecretName }}

---

{{- $azureSecretNamePrefix := .Values.pagopaProxy.secrets.azureSecretNamePrefix -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the certificate to retrieve from the Azure Keyvault
  name: {{ $azureSecretNamePrefix }}-io-certs
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.pagopaProxy.secrets.azureKeyvaultName }}
    object:
      type: certificate
      # Name of the certificate to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-io-certs
  output:
    secret:
      name: {{ .Values.pagopaProxy.secrets.kubernetesIoCertSecretName }}
      type: kubernetes.io/tls

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pagopaProxy.secrets.kubernetesPagopaCaChainCertsSecretName }}
type: Opaque

---

{{- $azureSecretNamePrefix := .Values.pagopaProxy.secrets.azureSecretNamePrefix -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to retrieve from the Azure Keyvault
  name: {{ $azureSecretNamePrefix }}-pagopa-ca-chain-certs
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.pagopaProxy.secrets.azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-pagopa-ca-chain-certs
  output:
    secret:
      name: {{ .Values.pagopaProxy.secrets.kubernetesPagopaCaChainCertsSecretName }}
      dataKey: ca.crt
