---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pagopa-proxy.fullname" . }}
  labels:
    app: {{ template "pagopa-proxy.name" . }}
    chart: {{ template "pagopa-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pagopaProxy.replicaCount }}
  {{- if .Values.pagopaProxy.strategy }}
  {{- with .Values.pagopaProxy.strategy }}
  strategy:
    type: {{ toYaml .type }}
    rollingUpdate:
      maxUnavailable: {{ toYaml .rollingUpdate.maxUnavailable }}
      maxSurge: {{ toYaml .rollingUpdate.maxSurge }}
  {{- end }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.pagopaProxy.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "pagopa-proxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pagopa-proxy.name" . }}
        release: {{ .Release.Name }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      # Configuration to match Nginx TLS proxy
      # hostnames, so redirecting traffic either
      # to gad-test or gad-prod host.
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "{{ .Values.pagopaProxy.env.proxy_internal_hostname }}"

      containers:
        # PagoPA Proxy
        - name: pagopa-proxy
          image: "{{ .Values.global.registry }}{{ .Values.pagopaProxy.images.pagopaProxy.repository }}:{{ tpl .Values.pagopaProxy.images.pagopaProxy.tag . }}"
          imagePullPolicy: {{ .Values.pagopaProxy.images.pagopaProxy.pullPolicy }}
          env:
            - name: "WINSTON_LOG_LEVEL"
              value: "{{ .Values.pagopaProxy.env.winston_log_level }}"
            - name: "PAGOPAPROXY_HOST"
              value: "{{ .Values.pagopaProxy.env.pagopaproxy_host }}"
            - name: "PAGOPAPROXY_PORT"
              value: "{{ .Values.pagopaProxy.env.pagopaproxy_port }}"
            - name: "PAGOPA_HOST"
              value: "http://{{ .Values.pagopaProxy.env.proxy_internal_hostname }}"
            - name: "PAGOPA_PORT"
              value: "80"
            - name: "PAGOPA_WS_URI"
              value: "{{ .Values.pagopaProxy.env.pagopa_ws_uri }}"
            - name: "PAGOPA_HOST_HEADER"
              value: "{{ .Values.pagopaProxy.env.proxy_internal_hostname }}"
            - name: "PAGOPA_TIMEOUT_MSEC"
              value: "{{ .Values.pagopaProxy.env.pagopa_timeout_msec }}"
            - name: "REDIS_DB_URL"
              value: "{{ .Values.pagopaProxy.env.redis_db_url }}"
            - name: "REDIS_DB_PORT"
              value: "{{ .Values.pagopaProxy.env.redis_db_port }}"
            - name: "REDIS_USE_CLUSTER"
              value: "{{ .Values.pagopaProxy.env.redis_use_cluster }}"

            # Secret names and values are automatically composed from the values file
            # using the format azureSecretName?azureSecretKeyName
            {{- $azureSecretName := .Values.pagopaProxy.secrets.azureSecretNamePrefix -}}
            {{- range .Values.pagopaProxy.secrets.azureSecretKeyNames }}
            {{- $azureSecretKeyNameUpper := . | upper }}
            - name: {{ regexReplaceAll "-" $azureSecretKeyNameUpper "_" }}
              value: {{ $azureSecretName }}@azurekeyvault?{{ . }}
            {{- end }}

          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5

          ports:
            - name: ppa-http
              containerPort: {{ .Values.pagopaProxy.services.pagopaProxy.httpPort.containerPort }}
              protocol: {{ .Values.pagopaProxy.services.pagopaProxy.httpPort.protocol }}
          resources:
{{ toYaml .Values.pagopaProxy.resources | indent 12 }}

        # PagoPA Nginx Proxy to originate TLS connections
        - name: pagopa-proxy-nginx-tls
          image: "{{ .Values.global.registry }}{{ .Values.pagopaProxy.images.pagopaProxyNginxTls.repository }}:{{ tpl .Values.pagopaProxy.images.pagopaProxyNginxTls.tag . }}"
          imagePullPolicy: {{ .Values.pagopaProxy.images.pagopaProxyNginxTls.pullPolicy }}
          env:
            - name: "PROXY_INTERNAL_HOSTNAME"
              value: "{{ .Values.pagopaProxy.env.proxy_internal_hostname }}"
            - name: "PROXY_EXTERNAL_HOSTNAME"
              value: "{{ .Values.pagopaProxy.env.proxy_external_hostname }}"
            - name: "PAGOPA_HOSTNAME"
              value: "{{ .Values.pagopaProxy.env.pagopa_hostname }}"
          command:
            - "/bin/sh"
          args:
            - "-c"
            - |
              envsubst '${PROXY_INTERNAL_HOSTNAME} ${PROXY_EXTERNAL_HOSTNAME} ${PAGOPA_HOSTNAME}' < /etc/nginx/conf.d/tmp/pagopa_proxy_nginx_tls.template > /etc/nginx/conf.d/pagopa_proxy_nginx_tls.conf &&
              exec nginx -g 'daemon off;'
          {{- with .Values.pagopaProxy.configs.pagopaProxyNginxTls.nginxConfig.volumeMountSettings }}
          volumeMounts:
            - name: pagopa-proxy-nginx-tls-config
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- with .Values.pagopaProxy.configs.pagopaProxyNginxTls.ioCertsConfig.volumeMountSettings }}
            - name: pagopa-proxy-nginx-tls-io-certs-config
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- with .Values.pagopaProxy.configs.pagopaProxyNginxTls.pagopaCaCertsConfig.volumeMountSettings }}
            - name: pagopa-proxy-nginx-tls-pagopa-ca-certs-config
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
          {{- end }}

          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: 443
              path: /healthz
              httpHeaders:
              - name: Host
                value: "{{ .Values.pagopaProxy.probes_host_header }}"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5

          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 443
              path: /healthz
              httpHeaders:
              - name: Host
                value: "{{ .Values.pagopaProxy.probes_host_header }}"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5

          ports:
            - name: ppa-nginx-http
              containerPort: {{ .Values.pagopaProxy.services.pagopaProxyNginxTls.httpPort.containerPort }}
              protocol: {{ .Values.pagopaProxy.services.pagopaProxyNginxTls.httpPort.protocol }}
          resources:
{{ toYaml .Values.pagopaProxy.resources | indent 12 }}

{{- with .Values.pagopaProxy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pagopaProxy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pagopaProxy.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

      volumes:
        - name: pagopa-proxy-nginx-tls-config
          configMap:
            name: {{ template "pagopa-proxy.fullname" . }}-nginx-tls-configmap
        - name: pagopa-proxy-nginx-tls-io-certs-config
          secret:
            secretName: {{ .Values.pagopaProxy.configs.pagopaProxyNginxTls.ioCertsConfig.volumeMountSettings.secretName }}
        - name: pagopa-proxy-nginx-tls-pagopa-ca-certs-config
          secret:
            secretName: {{ .Values.pagopaProxy.configs.pagopaProxyNginxTls.pagopaCaCertsConfig.volumeMountSettings.secretName }}
