---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "pagopa-proxy.fullname" . }}
  labels:
    app: {{ template "pagopa-proxy.name" . }}
    chart: {{ template "pagopa-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.pagopaProxy.services.pagopaProxy.httpPort.type }}
  ports:
    - port: {{ .Values.pagopaProxy.services.pagopaProxy.httpPort.servicePort }}
      targetPort: {{ .Values.pagopaProxy.services.pagopaProxy.httpPort.containerPort }}
  selector:
    app: {{ template "pagopa-proxy.name" . }}
    release: {{ .Release.Name }}
