---

{{- $azureSecretNamePrefix := .Values.ioOnboardingPaApi.secrets.azureSecretNamePrefix -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the certificate to retrieve from the Azure Keyvault
  name: {{ $azureSecretNamePrefix }}-spid-certs
  namespace: onboarding
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.ioOnboardingPaApi.secrets.azureKeyvaultName }}
    object:
      type: certificate
      # Name of the certificate to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-spid-certs
  output:
    secret:
      name: {{ .Values.ioOnboardingPaApi.secrets.kubernetesSpidCertsSecretName }}
      type: kubernetes.io/tls
