---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ioOnboardingPaApi.secrets.kubernetesSecretName }}
type: Opaque

---

{{- $azureSecretNamePrefix := .Values.ioOnboardingPaApi.secrets.azureSecretNamePrefix -}}
{{- $azureKeyvaultName := .Values.ioOnboardingPaApi.secrets.azureKeyvaultName -}}
{{- $kubernetesSecretName := .Values.ioOnboardingPaApi.secrets.kubernetesSecretName -}}

{{- range .Values.ioOnboardingPaApi.secrets.azureSecretNameSuffixes }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: {{ $azureSecretNamePrefix }}-{{ . }}
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ $azureKeyvaultName }}
    object:
      type: secret
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-{{ . }}
  output:
    secret:
      # Name of the secret in Kubernetes
      name: {{ $kubernetesSecretName }}
      # Name of key in the secret in Kubernetes
      dataKey: {{ regexReplaceAll "-" . "_" }}
---
{{- end }}

{{- $azureSecretNamePrefix := .Values.ioOnboardingPaApi.secrets.azureSecretNamePrefix -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the certificate to retrieve from the Azure Keyvault
  name: {{ $azureSecretNamePrefix }}-spid-certs
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ .Values.ioOnboardingPaApi.secrets.azureKeyvaultName }}
    object:
      type: certificate
      # Name of the certificate to retrieve from the Azure Keyvault
      name: {{ $azureSecretNamePrefix }}-spid-certs
  output:
    secret:
      name: {{ .Values.ioOnboardingPaApi.secrets.kubernetesSpidCertsSecretName }}
      type: kubernetes.io/tls
