---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "io-onboarding-pa-api.fullname" . }}-http
  labels:
    app: {{ template "io-onboarding-pa-api.name" . }}
    chart: {{ template "io-onboarding-pa-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ioOnboardingPaApi.services.backendHttp.type }}
  ports:
    - name: onboard-pa-api
{{ toYaml .Values.ioOnboardingPaApi.services.backendHttp | indent 6 }}
  selector:
    app: {{ template "io-onboarding-pa-api.name" . }}
    release: {{ .Release.Name }}
