---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.developerPortalBackend.secrets.kubernetesSecretName }}
type: Opaque

---

{{- $azureSecretName := .Values.developerPortalBackend.secrets.azureSecretNamePrefix -}}
{{- $azureKeyvaultName := .Values.developerPortalBackend.secrets.azureKeyvaultName -}}
{{- $kubernetesSecretName := .Values.developerPortalBackend.secrets.kubernetesSecretName -}}

apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  # Name of the secret to reference from deployment
  name: {{ $azureSecretName }}
  namespace: default
spec:
  vault:
    # Name of the Azure Keyvault
    name: {{ $azureKeyvaultName }}
    object:
      # Name of the secret to retrieve from the Azure Keyvault
      name: {{ $azureSecretName }}
      type: multi-key-value-secret
      contentType: application/x-json
  output:
    secret:
      # Name of the secret in Kubernetes
      name: {{ $kubernetesSecretName }}
