---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-custom
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-custom
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
