---

# Bind the admin AD group to the cluster-admin role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-admins
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  # io-prod-group-k8s-admins
  name: "27bef087-6880-4b89-a3e9-759587cd1a84"

---

# Create an onboarding role to only provide
# full access to the onboarding namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: onboarding
  namespace: onboarding
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---

# Bind the onboarding AD group to the onboarding role
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: onboarding
  namespace: onboarding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onboarding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  # io-prod-group-k8s-onboarding
  name: "4385ab20-b5f0-45bb-9aef-77a9ec46e2b5"
