---

apiVersion: v1

kind: Service
metadata:
  name: {{ template "pagopa-proxy.fullname" . }}
  labels:
    app: {{ template "pagopa-proxy.name" . }}
    chart: {{ template "pagopa-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.pagopaProxy.services.httpPort.type }}
  ports:
    - name: http-port
{{ toYaml .Values.pagopaProxy.services.httpPort | indent 6 }}
  selector:
    app: {{ template "pagopa-proxy.name" . }}
    release: {{ .Release.Name }}
