---

# The configuration extends the default values of the pagopa-proxy helm-chart.
# It should be used to instatiate a production pagopa-proxy instance.
#
# This file should be applied together (and before) the config/prod.yaml file, if deployed
# in the prod environment: helm install -f configs/pagopa-proxy-prod.yaml -f configs/prod.yaml -n pagopa-proxy pagopa-proxy

# PAGOPA-PROXY - start

pagopaProxy:
  env:
    proxy_external_hostname: "pagopa-prod.io.italia.it"
    pagopa_hostname: "https://gad.pagopa.gov.it"

  secrets:
    kubernetesSecretName: pagopa-proxy-prod-secrets
    azureSecretNamePrefix: k8s-pagopa-proxy-prod-secrets
    kubernetesPagopaCaChainCertsSecretName: pagopa-proxy-prod-pagopa-ca-chain-certs

  configs:
    pagopaProxyNginxTls:
      pagopaCaCertsConfig:
        volumeMountSettings:
          secretName: pagopa-proxy-pagopa-ca-prod-certs
      ioCertsConfig:
        volumeMountSettings:
          secretName: pagopa-proxy-io-prod-certs

  probes_host_header: pagopa-prod.io.italia.it

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "default/pagopa-proxy-pagopa-ca-prod-certs"
    hosts:
      - pagopa-prod.io.italia.it
    tls:
      - hosts:
        - pagopa-prod.io.italia.it
        secretName: pagopa-proxy-io-prod-certs

# PAGOPA-PROXY - end