---

global:
  registry: ''

# APP-BACKEND - start

appBackend:
  env:
    api_url: "https://io-prod-apim-01.azure-api.net/api/v1"
    azure_nh_hub_name: "io-prod-nh-nh-01"
    node_env: "production"
    redis_url: "io-prod-redis-cache-01.redis.cache.windows.net"
    saml_callback_url: "https://app-backend.io.italia.it/assertionConsumerService"
    spid_testenv_url: "https://spid-testenv.io.italia.it"

  ingress:
    hosts:
      - app-backend.prod.io.italia.it
      - app-backend.io.italia.it
    tls:
      - hosts:
          - app-backend.prod.io.italia.it
          - app-backend.io.italia.it
        secretName: app-backend-tls

# APP-BACKEND - end

# SPID-TESTENV - start

spidTestenv:
  ingress:
    hosts:
      - spid-testenv.prod.io.italia.it
      - spid-testenv.io.italia.it
    tls:
      - hosts:
          - spid-testenv.prod.io.italia.it
          - spid-testenv.io.italia.it
        secretName: spid-testenv-tls

# SPIND-TESTENV - end

# IO-ONBOARDING-PA-API - start

ioOnboardingPaApi:
  env:
    client_spid_login_redirection_url: https://pa-onboarding.io.italia.it
    client_spid_success_redirection_url: https://pa-onboarding.io.italia.it/dashboard
    saml_callback_url: "https://api.pa-onboarding.io.italia.it/assertion-consumer-service"
    spid_testenv_url: "https://spid-testenv.io.italia.it"

  ingress:
    hosts:
      - api.pa-onboarding.prod.io.italia.it
      - api.pa-onboarding.io.italia.it
    tls:
      - hosts:
          - api.pa-onboarding.prodio.italia.it
          - api.pa-onboarding.io.italia.it

# IO-ONBOARDING-PA-API - end

# IO-ONBOARDING-PA - start

ioOnboardingPa:
  env:
    io_onboarding_pa_api_host: https://api.pa-onboarding.io.italia.it

  ingress:
    hosts:
      - pa-onboarding.prod.io.italia.it
      - pa-onboarding.io.italia.it
    tls:
      - hosts:
          - pa-onboarding.prod.io.italia.it
          - pa-onboarding.io.italia.it

# IO-ONBOARDING-PA - end
