---

global:
  registry: ''

# APP-BACKEND - start

appBackend:
  env:
    api_url: "https://io-prod-fn-2-app.azurewebsites.net/api/v1"
    azure_nh_hub_name: "io-prod-nh-nh-01"
    node_env: "production"
    redis_url: "io-prod-redis-cache-01.redis.cache.windows.net"
    saml_issuer: "https://app-backend.io.italia.it"
    saml_callback_url: "https://app-backend.io.italia.it/assertionConsumerService"
    spid_testenv_url: "https://spid-testenv.io.italia.it"

  secrets:
    azureKeyvaultName: io-prod-keyvault

  ingress:
    hosts:
      - app-backend.io.italia.it
    tls:
      - hosts:
          - app-backend.io.italia.it
        secretName: app-backend-tls

# APP-BACKEND - end

# SPID-TESTENV - start

spidTestenv:
  ingress:
    hosts:
      - spid-testenv.io.italia.it
    tls:
      - hosts:
          - spid-testenv.io.italia.it
        secretName: spid-testenv-tls

  configs:
    config: |
      # Identity provider configuration

      base_url: "https://spid-testenv.io.italia.it"

      # To sign SAML messages

      key_file: "/app/conf/idp.key"
      cert_file: "/app/conf/idp.crt"

      # Service provider configuration

      metadata:
        remote:
          - url: "https://api.pa-onboarding.io.italia.it/metadata"
          - url: "https://app-backend.io.italia.it/metadata"

      # Web server configuration

      debug: false

      host: 0.0.0.0
      port: 8088

      # HTTPS is handled by Kubernetes ingress

      https: false

      # Identity provider endpoints
      endpoints:
        single_sign_on_service: "/sso"
        single_logout_service: "/slo"

# SPIND-TESTENV - end

# IO-ONBOARDING-PA-API - start

ioOnboardingPaApi:
  env:
    client_domain: https://pa-onboarding.io.italia.it:443
    client_spid_login_redirection_url: https://pa-onboarding.io.italia.it
    client_spid_success_redirection_url: https://pa-onboarding.io.italia.it/dashboard
    cookie_domain: .io.italia.it
    node_env: production
    saml_issuer: "https://api.pa-onboarding.io.italia.it"
    saml_callback_url: "https://api.pa-onboarding.io.italia.it/assertion-consumer-service"
    spid_testenv_url: "https://spid-testenv.io.italia.it"

  secrets:
    azureKeyvaultName: io-prod-keyvault

  ingress:
    hosts:
      - api.pa-onboarding.io.italia.it
    tls:
      - hosts:
          - api.pa-onboarding.io.italia.it
        secretName: io-onboarding-pa-api-prod-tls

# IO-ONBOARDING-PA-API - end

# IO-ONBOARDING-PA - start

ioOnboardingPa:
  env:
    io_onboarding_pa_api_host: https://api.pa-onboarding.io.italia.it
    io_onboarding_pa_show_fake_idp: 0
    io_onboarding_pa_is_mock_env: 0
    io_onboarding_pa_session_token_domain: .io.italia.it

  ingress:
    hosts:
      - pa-onboarding.io.italia.it
    tls:
      - hosts:
          - pa-onboarding.io.italia.it
        secretName: io-onboarding-pa-prod-tls

# IO-ONBOARDING-PA - end

# DEVELOPER-PORTAL-BACKEND - start

developerPortalBackend:
  env:
    arm_apim: io-prod-apim-01
    arm_resource_group: io-prod-rg
    client_name: io-prod-developer-portal
    post_login_url: https://developer.io.italia.it
    post_logout_url: https://developer.io.italia.it
    reply_url: https://developer.io.italia.it

  secrets:
    azureKeyvaultName: io-prod-keyvault

  ingress:
    hosts:
      - backend.developer.io.italia.it
    tls:
      - hosts:
          - backend.developer.io.italia.it
        secretName: developer-portal-backend-prod-tls

# DEVELOPER-PORTAL-BACKEND - end

# DEVELOPER-PORTAL-FRONTEND - start

developerPortal:
  env:
    io_developer_portal_port: 80
    io_developer_portal_backend: https://backend.developer.io.italia.it
    io_developer_portal_apim_base_url: https://api.io.italia.it/api/v1
    io_developer_portal_base_url: /
    io_developer_portal_public_path: /

  ingress:
    hosts:
      - developer.prod.io.italia.it
      # - developer.io.italia.it
    tls:
      - hosts:
          - developer.prod.io.italia.it
          # - developer.io.italia.it
        secretName: developer-portal-frontend-prod-tls

# DEVELOPER-PORTAL-FRONTEND - end

# PAGOPA-PROXY - start

pagopaProxy:
  env:
    proxy_external_hostname: "pagopa-test.io.italia.it"
    redis_db_url: "io-prod-redis-cache-01.redis.cache.windows.net"

  secrets:
    azureKeyvaultName: io-prod-keyvault

  probes_host_header: pagopa-test.io.italia.it

  ingress:
    hosts:
      - pagopa-test.io.italia.it
    tls:
      - hosts:
        - pagopa-test.io.italia.it
        secretName: pagopa-proxy-test-io-certs

# PAGOPA-PROXY - end
