---

apiVersion: v1
kind: Secret
metadata:
  name: io-onboarding-pa-api-secrets
type: Opaque
stringData:
  email-password: YOUR_EMAIL_PASSWORD
  postgresql-password: YOUR_POSTGRESQL_PASSWORD_HERE
  postgresql-replication-password:  YOUR_POSTGRESQL_REPLICATION_PASSWORD_HERE
