---

global:
  registry: ''

postgresql:
  global:
    postgresql:
      postgresqlUsername: io-onboarding-pa-api
      postgresqlDatabase: io-onboarding-pa-api
      existingSecret: io-onboarding-pa-api-secrets
  persistence:
    existingClaim: io-onboarding-pa-api-postgres

ioOnboardingPaApi:

  replicaCount: 1

  images:
    backend:
      repository: docker.io/teamdigitale/io-onboarding-pa-api
      tag: latest
      pullPolicy: Always

  backend:
    host: backend

  env:
    api_base_path: /api/v1
    backend_port: "3000"
    client_domain: https://pa-onboarding.dev.io.italia.it
    client_spid_error_redirection_url: /error.html
    client_spid_login_redirection_url: https://pa-onboarding.dev.io.italia.it
    client_spid_success_redirection_url: https://pa-onboarding.dev.io.italia.it/dashboard
    cookie_domain: .dev.io.italia.it
    node_env: development
    postgresql_host: io-onboarding-pa-api-postgresql
    postgresql_database: io-onboarding-pa-api
    postgresql_username: io-onboarding-pa-api
    saml_accepted_clock_skew_ms: "-1"
    saml_attribute_consuming_service_index: "0"
    saml_callback_url: "https://api.pa-onboarding.dev.io.italia.it/assertion-consumer-service"
    saml_issuer: "https://api.pa-onboarding.dev.io.italia.it"
    spid_autologin: ""
    spid_testenv_url: "https://spid-testenv.dev.io.italia.it"
    idp_metadata_url: "https://registry.spid.gov.it/metadata/idp/spid-entities-idps.xml"
    saml_cert_path: "/usr/src/app/certs/cert.pem"
    saml_key_path: "/usr/src/app/certs/key.pem"
    token_duration_in_seconds: "3600" #1 hour
    email_user: "portaleonboarding@gmail.com"
    email_smtp_host: "smtp.gmail.com"
    email_smtp_port: "465"
    email_smtp_secure: "true"
    email_sender: "portaleonboarding@gmail.com"
    indicepa_administrations_url: "https://raw.githubusercontent.com/teamdigitale/io-onboarding-pa-api/master/development-data/administrations.txt"
    arss_wsdl_url: "https://arss.demo.firma-automatica.it/ArubaSignService/ArubaSignService?wsdl"
    arss_identity_type_otp_auth: "demoprod"
    arss_identity_user: "titolare_rem"

  secrets:
    azureKeyvaultName: io-dev-keyvault
    kubernetesSpidCertsSecretName: io-onboarding-pa-api-spid-certs
    kubernetesSecretName: io-onboarding-pa-api-secrets
    azureSecretNamePrefix: k8s-io-onboarding-pa-api-secrets
    azureSecretKeyNames:
      - email-password
      - postgresql-password
      - postgresql-replication-password
      - arss-identity-otp-pwd
      - arss-identity-user-pwd

  spidCert:
    mountPath: "/usr/src/app/certs"
    readOnly: true

  services:
    backendHttp:
      port: 3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "azure/application-gateway"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/acme-challenge-type: "http01"
    path: /
    hosts:
      - api.pa-onboarding.dev.io.italia.it
    tls:
      - hosts:
          - api.pa-onboarding.dev.io.italia.it
        secretName: io-onboarding-pa-api-dev-tls

  resources:
    # For each of the following objects, set limits
    # removing the curly brackets after resources and
    # uncommenting the lines below.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    backend: {}

  nodeSelector: {}

  tolerations: {}

  affinity: {}
