---

global:
  registry: ''

ioOnboardingPa:

  replicaCount: 1

  images:
    frontend:
      repository: teamdigitale/io-onboarding-pa
      tag: latest
      pullPolicy: Always

  env:
    io_onboarding_pa_api_host: https://api.pa-onboarding.dev.io.italia.it
    io_onboarding_pa_api_port: 443
    io_onboarding_pa_show_fake_idp: 1

  services:
    http:
      port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    path: /
    hosts:
      - pa-onboarding.dev.io.italia.it
    tls:
      - hosts:
          - pa-onboarding.dev.io.italia.it
        secretName: io-onboarding-pa-dev-tls

  resources:
    frontend:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  nodeSelector: {}

  tolerations: {}

  affinity: {}
