---

global:
  registry: ''

ioOnboardingPa:

  replicaCount: 1

  images:
    frontend:
      repository: teamdigitale/io-onboarding-pa
      tag: latest
      pullPolicy: Always

  env:
    io_onboarding_pa_api_host: https://api.pa-onboarding.dev.io.italia.it
    io_onboarding_pa_api_port: 443
    io_onboarding_pa_show_fake_idp: 1
    io_onboarding_pa_is_mock_env: 0
    io_onboarding_pa_session_token_domain: .dev.io.italia.it

  services:
    http:
      port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "azure/application-gateway"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      cert-manager.io/acme-challenge-type: "http01"
    path: /
    hosts:
      - pa-onboarding.dev.io.italia.it
    tls:
      - hosts:
          - pa-onboarding.dev.io.italia.it
        secretName: io-onboarding-pa-dev-tls

  resources:
    # For each of the following objects, set limits
    # removing the curly brackets after resources and
    # uncommenting the lines below.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
    frontend: {}

  nodeSelector: {}

  tolerations: {}

  affinity: {}
