---

# Firewalld already controlls iptables, so i can disable it
- name: Disabled firewalld
  systemd:
    name: firewalld
    enabled: no
    masked: yes

- name: Install iptables-services
  package:
    name: iptables-services
    state: present

- name: Enable iptables
  systemd:
    name: iptables
    state: started
    enabled: yes

- name: Save iptables configurations
  shell: service iptables save
